### ISSUE TITLE
Multi-byte character corruption on chunk boundaries

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/serpapi-javascript#22]
A customer reported that a question mark symbol is returned in `snippet` or `extracted_snippet.original` in the response from our Google Maps Reviews API sometimes. I was able to reproduce it using our `serpapi` package:

<img width="1144" alt="image" src="https://github.com/serpapi/serpapi-javascript/assets/144151895/dd7df32f-64b0-402c-9d4d-ed5b412ce689">

[`serpapi` package code](https://gist.github.com/martin-serpapi/da102985c5c8728f52da96d9cc744463)

However, the issue is not reproducible when sending requests to our Google Maps Reviews API directly with `axios`:

![image](https://github.com/serpapi/serpapi-javascript/assets/144151895/6234bd0d-a744-4a87-a5c6-4b1c2cf352f8)

[`axios` code](https://gist.github.com/martin-serpapi/1e0cad445d18ba2a301638ccfddf0166)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060603?view=List)

**Comment by LrDaniel** [comment]
Also can happen on the name

**Comment by Freaky** [comment]
I suspect because we're reading data in chunks from the HTTP response and directly appending it to a string, if a chunk happens to end in the middle of a multibyte character JS considers it corrupt and inserts a Unicode Replacement Character - this would explain why they come in pairs.

I'm still waiting for Deno to build, but I suspect something like this is needed:

```diff
diff --git src/utils.ts src/utils.ts
index ef49a2a..99aecb6 100644
--- src/utils.ts
+++ src/utils.ts
@@ -1,6 +1,7 @@
 import { version } from "../version.ts";
 import https from "node:https";
 import qs from "node:querystring";
+import { StringDecoder } from "node:string_decoder";
 import { RequestTimeoutError } from "./errors.ts";

 /**
@@ -63,15 +64,17 @@ export function execute(
   return new Promise((resolve, reject) => {
     let timer: number;
     const req = https.get(url, (resp) => {
+      const decoder = new StringDecoder("utf8");
       let data = "";

       // A chunk of data has been recieved.
       resp.on("data", (chunk) => {
-        data += chunk;
+        data += decoder.write(chunk);
       });

       // The whole response has been received. Print out the result.
       resp.on("end", () => {
+        data += decoder.end();
         try {
           if (resp.statusCode == 200) {
             resolve(data);
```
