### ISSUE TITLE
TypeError: AbortSignal.timeout is not a function

### ISSUE THREAD

**Issue by pawKer** [serpapi/serpapi-javascript#6]
I seem to be getting the same on Node 17.
I'm calling `getJson` like so:

```
const params = {
  q: 'keyword',
  location: 'Greater London,England,United Kingdom',
  gl: 'gb',
  hl: 'en'
}
await getJson("google", params)
```

And I am getting the following error:

```
TypeError: AbortSignal.timeout is not a function
    at Object.execute (file:///<redacted>/node_modules/serpapi/esm/src/utils.js:80:29)
    at getJson (file:///<redacted>/node_modules/serpapi/esm/src/serpapi.js:58:39)
```

_Originally posted by @pawKer in https://github.com/serpapi/serpapi-javascript/issues/4#issuecomment-1412886906_

**Comment by sebastianquek** [comment]
I've tried it locally with node v17.9.1 and it works. Could you provide more information about your environment?

**Comment by pawKer** [comment]
I've just installed node v17.9.1 and this is not happening anymore 🤔 . Changed back to node v17.0.0 and it happened again so it seems to be related to that. I'm on Windows and was running this in git bash in VS Code, npm version is v8.1.0.

**Comment by sebastianquek** [comment]
That's interesting, turns out that Node's AbortSignal.timeout implementation was added back in v17.3.0, https://nodejs.org/api/globals.html#static-method-abortsignaltimeoutdelay

![image](https://user-images.githubusercontent.com/577802/216504723-fa018c34-756d-4d0d-8670-11a3129feef9.png)

I've added a [restriction on the supported Node engines](https://github.com/serpapi/serpapi-javascript/commit/58c253bae9b018c48602f4aafe670eab1fb642b5) which will be pushed in the next release.

Thanks for reporting this @pawKer 😄

**Comment by pawKer** [comment]
No worries, thank you for looking into this!

**Comment by hartator** [comment]
> I've added a [restriction on the supported Node engines](https://github.com/serpapi/serpapi-javascript/commit/58c253bae9b018c48602f4aafe670eab1fb642b5) which will be pushed in the next release.

Wouldn't this exclude too many Node.js versions?

https://nodesource.com/blog/node-by-numbers-2020 These are numbers from 2020. However by extrapolating these numbers to similar distributions for the missing last 2 years and last 2 versions, a Node.js 16 and above requirement sounds like our library will be excluding 60 to 80% of Node.js users?

**Comment by sebastianquek** [comment]
@hartator How about we monitor this to see if it continues to be an issue for users?

We can remove this dependency on AbortSignal.timeout, though at the baseline I don't think we should go below Node 14 whose EOL is slated for 2023-04-30. Even GitHub has decided to shift all its Actions to use Node 16: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

EDIT: I'm in the midst of relaxing the restrictions on the supported Node engines.
